### PR TITLE
Add external installation url

### PR DESCRIPTION
**Pull request by sheff146**
Update TS types, validator, tests.

### CODE REVIEW

**Comment by palootcenas-outreach** [comment]
What is the reason we need the external install url in our SDK?
I thought the SDK is only for apps/extensions installed normally (not externally).

**Comment by palootcenas-outreach** [comment]
We need to bump up the version in `package.json` I guess.

**Comment by nimal-outreach** [comment]
@sheff146 what have happened with this PR? Is it abandoned?

**Comment by sheff146** [comment]
Yes, it's not needed so far. Closing.

**Pull request closed without merging**
